#os: test

init:
- appveyor version

build_script: 
  - set MSYSTEM=MINGW64
  - '"C:\msys64\usr\bin\bash" -l -c "cd /c/projects/appveyor-sh-bug && ./example.sh"'
#  - C:\msys64\usr\bin\bash -l -c "exec 3<&0 </dev/null"
  - ps: Start-Process "C:\msys64\usr\bin\bash" "-l","-c",'"cd /c/projects/appveyor-sh-bug && ./example.sh"' -RedirectStandardOutput out.txt -RedirectStandardError err.txt -Wait
  - ps: Get-Content .\out.txt
  - ps: Get-Content .\err.txt

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
