build_script: 
  - set MSYSTEM=MINGW64
  - "C:\Program Files\Git\usr\bin\bash.exe" -l -c "cd /c/projects/appveyor-sh-bug && ./example.sh"
#  - C:\msys64\usr\bin\bash -l -c "exec 3<&0 </dev/null"

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
